module.exports = {
  russia: 'Rússia',
  saudiArabia: 'Arábia Saudita',
  egypt: 'Egito',
  uruguay: 'Uruguai',
  morocco: 'Marrocos',
  spain: 'Espanha',
  australia: 'Australia',
  irIran: 'Irã',
  portugal: 'Portugal',
  france: 'França',
  argentina: 'Argentina',
  iceland: 'Islândia',
  peru: 'Peru',
  denmark: 'Dinamarca',
  nigeria: 'Nigéria',
  croatia: 'Croácia',
  costaRica: 'Costa Rica',
  serbia: 'Sérvia',
  germany: 'Alemanha',
  mexico: 'México',
  brazil: 'Brasil',
  switzerland: 'Suiça',
  southKorea: 'Coréia do Sul',
  belgium: 'Bélgica',
  panama: 'Panamá',
  tunisia: 'Tunísia',
  england: 'Inglaterra',
  colombia: 'Colômbia',
  japan: 'Japão',
  poland: 'Polônia',
  senegal: 'Senegal',
  sweden: 'Suécia'
}