module.exports = {
  russia: 'Russia',
  saudiArabia: 'Saudi Arabia',
  egypt: 'Egypt',
  uruguay: 'Uruguay',
  morocco: 'Morocco',
  spain: 'Spain',
  australia: 'Australia',
  irIran: 'Ir Iran',
  portugal: 'Portugal',
  france: 'France',
  argentina: 'Argentina',
  iceland: 'Iceland',
  peru: 'Peru',
  denmark: 'Denmark',
  nigeria: 'Nigeria',
  croatia: 'Croatia',
  costaRica: 'Costa Rica',
  serbia: 'Serbia',
  germany: 'Germany',
  mexico: 'Mexico',
  brazil: 'Brazil',
  switzerland: 'Switzerland',
  southKorea: 'South Korea',
  belgium: 'Belgium',
  panama: 'Panama',
  tunisia: 'Tunisia',
  england: 'England',
  colombia: 'Colombia',
  japan: 'Japan',
  poland: 'Poland',
  senegal: 'Senegal',
  sweden: 'Sweden'
}