'use strict'

const usEnDictionary = {
  passwordAlert: 'Password must be at least 8 characters, 1 special char, 1 Capital Letter, 1 Number and 1 lowerCase',
  alreadyUsed: 'Email or UserName already used',
  userNameAlreadyUsed: 'This userName is already used by other account',
  emailAlreadyUsed: 'This email is already used by other account',
  invalidLogin: 'User or Password incorrect, try again',
  notAEmail: 'Not is a valid email',
  invalidPassword: 'Password incorrect, try again',
  tooManyInvalidPassword: 'You did some many requests with wrong passwords, wait 1 hour to try it again',
  tooLongUserName: 'Too long UserName, please use a smaller one',
  tooLongName: 'Too long name, please use a smaller one',
  tooLongDescription: 'Too long description, please use a smaller one',
  friendshipRequest: '{{userName}} wants to be your friend',
  guessLeagueRequest: '{{userName}} is inviting you to participate of the {{guessLeagueName}} GuessLeague',
  userNotFound: '{{userName}} not found',
  userNotFoundImpersonal: 'User not found',
  notFriends: 'The users are not friend',
  notificationExists: 'Notification already sent',
  alreadyFriends: 'You are already friends',
  teamNotFound: 'Team not found',
  championshipNotFound: 'Championship not found',
  guessLineNotFound: 'GuessLine not found',
  roundNotFound: 'Fixture not found',
  sameTeams: 'You cannot repeat the teams that you support',
  alreadyAdd: 'Already add',
  matchDuplicated: 'You cannot do predictions to the same match at the same request',
  userRefDuplicated: 'You cannot invited the same user twice',
  guessLineInactive: 'This guessLine is not active',
  userNotAddedAtGuessLine: 'You are not at guessline\'s list',
  notAtGuessLine: 'Not at guessLine',
  anyGuessLineFound: 'No guessLines',
  anyGuessLeagueFound: 'No guessLeagues',
  admNotQuitGle: 'You are a administrator. If you want to leave the GuessLeague, you need to quit administration first',
  alreadyAdm: 'You are administrator already',
  youCantBeTheUserAndUserAdm: 'The userRef must to be different from userRefToAdm',
  tooFewAdms: 'You cannot leave the GuessLeague. You, at least, need to add someone to administration before',
  notAtGuessLeague: 'You are not at GuessLeague',
  someWrongAtInvite: 'Something wrong happened at the invite',
  notFriendsAtInvite: 'There are user not friends at inviteads list'
}

module.exports = usEnDictionary