'use strict'

const ptBrDictionary = {
  passwordAlert: 'A Senha deve conter ao menos 8 caracteres, 1 caracter especial, 1 Letra Maiúscula, 1 número e 1 letra Minúscula',
  alreadyUsed: 'Email ou UserName já está em uso',
  userNameAlreadyUsed: 'Esse userName já está em uso por outra conta',
  emailAlreadyUsed: 'Esse Email já está em uso por outra conta',
  invalidLogin: 'Usuário ou Senha incorreta, tente novamente',
  notAEmail: 'Não recebemos um email válido',
  invalidPassword: 'Senha incorreta, tente novamente',
  tooManyInvalidPassword: 'Você fez muitas requisições com senhas erradas, espere 1 hora para tentar novamente',
  tooLongUserName: 'UserName muito longo, por favor use um menor',
  tooLongName: 'Nome muito longo, por favor use um menor',
  tooLongDescription: 'Descrição muito longa, por favor use uma menor',
  friendshipRequest: '{{userName}} quer começar uma amizade',
  guessLeagueRequest: '{{userName}} esta te convidando para participar da GuessLeague {{guessLeagueName}}',
  userNotFound: '{{userName}} não encontrado',
  notFriends: 'Os usuários não são amigos',
  notificationExists: 'Notificação já enviada',
  alreadyFriends: 'Você já são amigos',
  teamNotFound: 'Equipe não encontrada',
  championshipNotFound: 'Campeonato não encontrado',
  guessLineNotFound: 'GuessLine não encontrada',
  roundNotFound: 'Rodada não encontrada',
  sameTeams: 'Vocâ não pode repetir as equipes que você torce',
  alreadyAdd: 'Já adicionado',
  matchDuplicated: 'Você não pode dar palpites na mesma partida numa única requisição',
  guessLineInactive: 'Essa guessLine não está ativa',
  userNotAddedAtGuessLine: 'Você não está na lista dessa GuessLine',
  notAtGuessLine: 'Não está adicionado na guessLine',
  anyGuessLineFound: 'Sem guessLines',
  anyGuessLeagueFound: 'Sem guessLeagues',
  admNotQuitGle: 'Você é um administrador. Para sair da GuessLeague é necessário que deixe de ser administrador antes.',
  alreadyAdm: 'Você já é administrador',
  youCantBeTheUserAndUserAdm: 'A userRef deve ser diferente da userRefToAdm',
  tooFewAdms: 'Você não pode sair da GuessLeague. Antes disso precisa adicionar ao menos uma pessoa como administrador',
  notAtGuessLeague: 'Você não esta na GuessLeague',
  someWrongAtInvite: 'Algo de errado aconteceu no envio do convite'
}

module.exports = ptBrDictionary